# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

costMatrix <- function(x1, x2, y1, y2, p1, p2) {
    .Call(`_gridOT_costMatrix`, x1, x2, y1, y2, p1, p2)
}

frankWolfeDiscrete <- function(x1, x2, mu, y1, y2, nu, p1, p2, startPivot, maxIt, tol, threads, returnIt, rightMargin) {
    .Call(`_gridOT_frankWolfeDiscrete`, x1, x2, mu, y1, y2, nu, p1, p2, startPivot, maxIt, tol, threads, returnIt, rightMargin)
}

frankWolfeEpsilonDiscrete <- function(x1, x2, mu, y1, y2, nu, p1, p2, startPivot, maxIt, tol, threads, returnIt, rightMargin, eps) {
    .Call(`_gridOT_frankWolfeEpsilonDiscrete`, x1, x2, mu, y1, y2, nu, p1, p2, startPivot, maxIt, tol, threads, returnIt, rightMargin, eps)
}

frankWolfeEpsilonHistogram <- function(x1, x2, mu, y1, y2, nu, p1, p2, startPivot, maxIt, tol, threads, returnIt, rightMargin, eps, width) {
    .Call(`_gridOT_frankWolfeEpsilonHistogram`, x1, x2, mu, y1, y2, nu, p1, p2, startPivot, maxIt, tol, threads, returnIt, rightMargin, eps, width)
}

northWestCorner <- function(mu, nu, threshold) {
    .Call(`_gridOT_northWestCorner`, mu, nu, threshold)
}

pivotMeasure <- function(from, to, mass, n1, n2, m1) {
    .Call(`_gridOT_pivotMeasure`, from, to, mass, n1, n2, m1)
}

transportPlan1d <- function(wa, wb, threshold = 1e-15) {
    .Call(`_gridOT_RcppTransportPlan1d`, wa, wb, threshold)
}

transportCost1d <- function(a, b, wa, wb, p, threshold = 1e-15) {
    .Call(`_gridOT_RcppTransportCost1d`, a, b, wa, wb, p, threshold)
}

transportCost <- function(x1, x2, mu, y1, y2, nu, p1, p2, xi, threshold) {
    .Call(`_gridOT_transportCost`, x1, x2, mu, y1, y2, nu, p1, p2, xi, threshold)
}

transportCostFromPlan <- function(from, to, mass, cost) {
    .Call(`_gridOT_transportCostFromPlan`, from, to, mass, cost)
}

transportPlan <- function(mu, nu, xi, threshold = 1e-15) {
    .Call(`_gridOT_transportPlan`, mu, nu, xi, threshold)
}

